#version: "3.8"
volumes:
  etc_wireguard:
  adguard_conf:
  adguard_work:

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    environment:
      - WG_HOST=${WG_HOST}
      - PASSWORD_HASH=${PASSWORD_HASH}
      - WG_DEFAULT_DNS=192.168.0.2
      - TZ=America/Santiago
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    volumes:
      - etc_wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
    restart: unless-stopped

  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    environment:
      - TZ=America/Santiago
    ports:
      - "53:53/tcp"    # DNS libre (no choca Pi-hole/Avahi)
      - "53:53/udp"
      - "8081:80/tcp"     # Web principal
      - "8444:443/tcp"    # HTTPS
      - "3000:3000/tcp"   # Setup inicial
    volumes:
      - adguard_work:/opt/adguardhome/work
      - adguard_conf:/opt/adguardhome/conf
    restart: unless-stopped
